# -*- coding: utf-8 -*-
"""Write sitemap.xml from the pages on disk.

Until 2026-09-30 the sitemap was hand-maintained from blocks the generators
printed, which is how it drifted (a Pro Plus image caption survived months
after Pro Plus was retired). Everything is now derived from each page:

  - every index.html outside SKIP, unless it is noindex
  - hreflang alternates copied from the page's own <link rel="alternate">,
    so the sitemap can never disagree with the HTML
  - <image:image> for app screens under /media/, captioned by their alt text
  - lastmod = today for a page that differs from HEAD (i.e. changed in this
    working tree), otherwise the date of the last commit that touched it.
    That keeps lastmod honest: re-running the build does not bump dates on
    pages whose content did not change.
"""
import datetime
import html
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = 'https://tovatranslate.app'
SKIP = {'.git', '_build', 'media', 'node_modules', 'lexicon'}
TODAY = datetime.date.today().isoformat()


def git(*a):
    return subprocess.run(['git', '-C', ROOT, *a], capture_output=True, text=True).stdout.strip()


def lastmod(rel):
    if subprocess.run(['git', '-C', ROOT, 'diff', '--quiet', 'HEAD', '--', rel]).returncode != 0 \
            or not git('ls-files', rel):
        return TODAY
    return git('log', '-1', '--format=%cs', '--', rel) or TODAY


def priority(url):
    path = url[len(BASE):]
    if path == '/':
        return '1.0', 'weekly'
    if re.fullmatch(r'/[a-z]{2}(-[a-z]{2})?/', path) or path in ('/translate/', '/tools/'):
        return '0.9', 'weekly'
    if '/translate/' in path or '/tools/' in path:
        return '0.8', 'monthly'
    if path in ('/privacy/', '/terms/'):
        return '0.3', 'yearly'
    return '0.6', 'monthly'


def main():
    rows = []
    for d, dirs, files in os.walk(ROOT):
        dirs[:] = sorted(x for x in dirs if x not in SKIP)
        if 'index.html' not in files:
            continue
        rel = os.path.relpath(os.path.join(d, 'index.html'), ROOT)
        s = open(os.path.join(ROOT, rel), encoding='utf-8').read()
        if re.search(r'<meta name="robots" content="[^"]*noindex', s):
            continue
        canon = re.search(r'<link rel="canonical" href="([^"]+)"', s)
        url = canon.group(1) if canon else BASE + '/' + os.path.dirname(rel) + '/'
        alts = re.findall(r'<link rel="alternate" hreflang="([^"]+)" href="([^"]+)"', s)
        imgs, seen = [], set()
        for src, alt in re.findall(r'<img[^>]*\bsrc="(/media/[^"]+)"[^>]*\balt="([^"]*)"', s):
            if src not in seen:
                seen.add(src)
                imgs.append((BASE + src, html.unescape(alt)))
        rows.append((url, rel, alts, imgs[:6]))

    order = lambda r: (r[0] != BASE + '/', '/translate/' in r[0], '/tools/' in r[0], r[0])
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"',
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
           '  <!-- Generated by _build/sitemap.py — do not edit by hand. -->']
    for url, rel, alts, imgs in sorted(rows, key=order):
        pr, cf = priority(url)
        out.append(f'  <url>\n    <loc>{url}</loc>\n    <lastmod>{lastmod(rel)}</lastmod>\n'
                   f'    <changefreq>{cf}</changefreq>\n    <priority>{pr}</priority>')
        for code, href in alts:
            out.append(f'    <xhtml:link rel="alternate" hreflang="{code}" href="{href}"/>')
        for loc, cap in imgs:
            out.append(f'    <image:image><image:loc>{loc}</image:loc>'
                       f'<image:caption>{html.escape(cap, quote=False)}</image:caption></image:image>')
        out.append('  </url>')
    out.append('</urlset>\n')
    open(os.path.join(ROOT, 'sitemap.xml'), 'w', encoding='utf-8').write('\n'.join(out))
    print(f'sitemap: {len(rows)} urls')


if __name__ == '__main__':
    main()
